extends CanvasLayer

@onready var buttons_container = $Control/VBoxContainer/ButtonsContainer
@onready var title_label = $Control/VBoxContainer/Title

var upgrades = [
	# Legacy placeholder list (unused). Choices are now generated by C# LoadoutManager.
]

func _ready():
	process_mode = Node.PROCESS_MODE_ALWAYS # Must run while paused
	visible = false
	
	if has_node("/root/GameManager"):
		get_node("/root/GameManager").level_up_choice_requested.connect(_on_level_up_requested)

func _on_level_up_requested():
	visible = true
	_generate_choices()

func _generate_choices():
	# Clean up old buttons
	for child in buttons_container.get_children():
		child.queue_free()

	var lm = _get_loadout_manager()
	var offers = []
	if lm:
		offers = lm.call("GenerateOffers", 4)
	
	for offer in offers:
		var btn = Button.new()
		btn.custom_minimum_size = Vector2(0, 60)
		btn.text = str(offer.get("name", "")) + "\n" + str(offer.get("desc", ""))
		var offer_id = str(offer.get("offer_id", ""))
		btn.pressed.connect(func(): _apply_offer(offer_id))
		buttons_container.add_child(btn)


func _get_loadout_manager() -> Node:
	if not has_node("/root/GameManager"):
		return null
	var gm = get_node("/root/GameManager")
	var player = gm.player_reference
	if not player:
		return null
	if player.has_node("LoadoutManager"):
		return player.get_node("LoadoutManager")
	return null


func _apply_offer(offer_id: String):
	var lm = _get_loadout_manager()
	if lm and offer_id != "":
		lm.call("ApplyOffer", offer_id)

	# Resume Game
	visible = false
	get_tree().paused = false
	if has_node("/root/GameManager"):
		get_node("/root/GameManager").resume_game()
