extends CanvasLayer

@onready var buttons_container = $Control/Content/Choices/ButtonsContainer
@onready var title_label = $Control/Content/Choices/Title
@onready var inventory_panel: Control = $Control/Content/InventoryDetailsPanel
@onready var detail_confirm_button: Button = $Control/Content/Choices/DetailConfirmButton

const SHORT_DESC_MAX_CHARS := 90

var _detail_mode := false
var _selected_offer_id := ""
var _offers_by_id: Dictionary = {}
var _current_offers: Array = []

var upgrades = [
	# Legacy placeholder list (unused). Choices are now generated by C# LoadoutManager.
]

func _ready():
	process_mode = Node.PROCESS_MODE_ALWAYS # Must run while paused
	visible = false
	if detail_confirm_button:
		detail_confirm_button.pressed.connect(_on_detail_confirm_pressed)
	if has_node("/root/Localization"):
		get_node("/root/Localization").language_changed.connect(func(_lang):
			_apply_language_to_ui()
			if visible:
				_render_choices(_current_offers)
		)
	_apply_language_to_ui()
	
	if has_node("/root/GameManager"):
		get_node("/root/GameManager").level_up_choice_requested.connect(_on_level_up_requested)

func _on_level_up_requested():
	visible = true
	_set_detail_mode(false)
	_selected_offer_id = ""
	_offers_by_id.clear()
	_current_offers = []
	if inventory_panel and inventory_panel.has_method("hide_details"):
		inventory_panel.call("hide_details")
	if inventory_panel and inventory_panel.has_method("refresh"):
		inventory_panel.call("refresh")
	_generate_choices()

func _generate_choices():
	# Clean up old buttons
	for child in buttons_container.get_children():
		child.queue_free()
	_offers_by_id.clear()

	var lm = _get_loadout_manager()
	var offers = []
	if lm:
		offers = lm.call("GenerateOffers", 4)
	_current_offers = offers
	_render_choices(offers)


func _render_choices(offers: Array) -> void:
	# Clean up old buttons
	for child in buttons_container.get_children():
		child.queue_free()
	_offers_by_id.clear()

	var loc := get_node("/root/Localization") if has_node("/root/Localization") else null

	for offer in offers:
		var btn = Button.new()
		btn.custom_minimum_size = Vector2(0, 80)
		btn.focus_mode = Control.FOCUS_NONE
		
		# Build content: [icon 32x32] [name + desc]
		var hbox := HBoxContainer.new()
		hbox.add_theme_constant_override("separation", 8)
		
		# Only add icon if one is available
		var icon_path := str(offer.get("icon_path", ""))
		if icon_path != "":
			var texrect := TextureRect.new()
			texrect.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
			texrect.custom_minimum_size = Vector2(40, 40)
			texrect.size_flags_horizontal = Control.SIZE_SHRINK_CENTER
			texrect.size_flags_vertical = Control.SIZE_SHRINK_CENTER
			texrect.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
			var tex: Texture2D = load(icon_path)
			if tex:
				texrect.texture = tex
			hbox.add_child(texrect)
		
		# Text content (name + description)
		var vbox := VBoxContainer.new()
		vbox.size_flags_horizontal = Control.SIZE_EXPAND_FILL
		vbox.custom_minimum_size = Vector2(300, 0)
		
		var ability_id := str(offer.get("target_id", ""))
		var fallback_name := str(offer.get("name", ""))
		var fallback_desc := str(offer.get("desc", ""))
		var action := str(offer.get("action", ""))
		var is_upgrade := bool(offer.get("is_upgrade", action == "Upgrade"))
		
		var name_label := Label.new()
		name_label.text = str(loc.ability_name(ability_id, fallback_name)) if (loc and ability_id != "") else fallback_name
		name_label.custom_minimum_size = Vector2(300, 0)
		
		var desc_label := Label.new()
		var base_desc := str(loc.ability_desc(ability_id, fallback_desc)) if (loc and ability_id != "") else fallback_desc
		if is_upgrade and loc:
			base_desc = "%s: %s" % [str(loc.t("ui.offer_upgrade", "Upgrade")), base_desc]
		desc_label.text = _shorten_desc(base_desc)
		desc_label.autowrap_mode = TextServer.AutowrapMode.AUTOWRAP_WORD
		desc_label.custom_minimum_size = Vector2(300, 0)
		
		vbox.add_child(name_label)
		vbox.add_child(desc_label)
		hbox.add_child(vbox)
		
		btn.add_child(hbox)

		var offer_id := str(offer.get("offer_id", ""))
		if offer_id != "":
			_offers_by_id[offer_id] = offer
		btn.pressed.connect(func(): _on_offer_pressed(offer_id))
		buttons_container.add_child(btn)

	# In detail mode, require a selection before confirm.
	_update_detail_confirm_state()


func _get_loadout_manager() -> Node:
	if not has_node("/root/GameManager"):
		return null
	var gm = get_node("/root/GameManager")
	var player = gm.player_reference
	if not player:
		return null
	if player.has_node("LoadoutManager"):
		return player.get_node("LoadoutManager")
	return null


func _apply_offer(offer_id: String):
	var lm = _get_loadout_manager()
	if lm and offer_id != "":
		lm.call("ApplyOffer", offer_id)

	# Resume Game
	visible = false
	get_tree().paused = false
	if has_node("/root/GameManager"):
		get_node("/root/GameManager").resume_game()


func _on_offer_pressed(offer_id: String) -> void:
	if offer_id == "":
		return

	if not _detail_mode:
		_apply_offer(offer_id)
		return

	_selected_offer_id = offer_id
	_update_detail_confirm_state()

	if inventory_panel and inventory_panel.has_method("show_offer_details"):
		var offer: Dictionary = _offers_by_id.get(offer_id, {})
		inventory_panel.call("show_offer_details", offer)
		return

	# Fallback: if no details UI exists, at least avoid applying immediately.
	# (No-op)


func _on_detail_confirm_pressed() -> void:
	if not _detail_mode:
		_set_detail_mode(true)
		return
	if _selected_offer_id == "":
		return
	_apply_offer(_selected_offer_id)


func _set_detail_mode(enabled: bool) -> void:
	_detail_mode = enabled
	if detail_confirm_button:
		_apply_language_to_ui()
	_update_detail_confirm_state()


func _apply_language_to_ui() -> void:
	if detail_confirm_button == null:
		return
	var loc := get_node("/root/Localization") if has_node("/root/Localization") else null
	if loc:
		detail_confirm_button.text = str(loc.t("ui.confirm", "Confirm")) if _detail_mode else str(loc.t("ui.details", "Details"))
	else:
		detail_confirm_button.text = "決定" if _detail_mode else "詳細を見る"


func _update_detail_confirm_state() -> void:
	if not detail_confirm_button:
		return
	if not _detail_mode:
		detail_confirm_button.disabled = false
		return
	detail_confirm_button.disabled = (_selected_offer_id == "")


func _shorten_desc(text: String) -> String:
	var s := text.strip_edges()
	if s == "":
		return ""
	s = s.replace("\n", " ").replace("\r", " ")
	while "  " in s:
		s = s.replace("  ", " ")
	if s.length() <= SHORT_DESC_MAX_CHARS:
		return s
	return s.substr(0, SHORT_DESC_MAX_CHARS - 1) + "…"
